"""Output orchestrator: query DB → render all artifacts → write files.

Updates `trip.my_maps_generated_at` after a successful run. The caller
(CLI) is responsible for choosing the output directory.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from travel_planner.db.query import DayView, PlaceView, TripView, load_days, load_places, load_trip
from travel_planner.output.csv import render_csv
from travel_planner.output.directions import render_daily_routes
from travel_planner.output.kml import render_kml
from travel_planner.output.places_index import render_places_index
from travel_planner.output.saveable import render_saveable_places


@dataclass
class GenerationReport:
    files_written: list[Path]
    places_total: int
    places_pinned: int  # have lat/lng (will appear on map)
    places_saveable: int  # have google_place_id (in saveable list)
    days_with_routes: int


def _map_name(trip: TripView) -> str:
    """Render the title displayed in My Maps. Format: `Name-YYYY-MM` (no slash)."""
    parts = [trip.name.split()[0]]
    if trip.start_date:
        parts.append(f"{trip.start_date.year:04d}-{trip.start_date.month:02d}")
    return "-".join(parts)


_README = """\
# Output artifacts

These files are regenerated by `tp map generate <slug>` from the markdown
in this trip directory. Don't edit by hand — edit the source markdown
and re-run.

## Files

- **my-maps.csv** — import into Google My Maps:
  1. Open https://www.google.com/mymaps → **+ Create a new map**.
  2. Click **Import** on the unnamed layer → upload `my-maps.csv`.
  3. Pick `latitude` + `longitude` as the location columns (skips
     Google's geocoder, deterministic for Japanese addresses).
  4. Pick `name` as the title column.
  5. After import: layer menu → **Style by data column** → `category` to
     get color-coded pins. The style rule persists across re-imports.

  To re-import after regenerating the CSV: open your existing map →
  layer menu → **Delete layer** → import the new CSV → choose
  **Replace layer**. Pin styles by `category` are preserved.

- **my-maps.kml** — alternative to CSV with per-category icons already
  applied. Same import flow, but skip the "Style by data column" step.

- **daily-routes.md** — one Google Maps directions URL per day. Tap on
  your phone → opens multi-stop nav directly in the Maps app.

- **places-index.md** — full reference of every place, grouped by
  category. Human-readable; not imported anywhere.

- **saveable-places.md** — one tap-to-save link per place, grouped by
  category. Tap on phone → opens place card in Maps → tap Save →
  add to a personal list (separate from My Maps).
"""


def generate(
    trip_id: str,
    output_dir: Path,
    conn: sqlite3.Connection,
) -> GenerationReport:
    """Generate all output artifacts for a trip. Returns a report."""
    trip = load_trip(conn, trip_id)
    if trip is None:
        raise ValueError(f"Trip {trip_id!r} not found in DB — run `tp parse {trip_id}` first.")
    places: list[PlaceView] = load_places(conn, trip_id)
    days: list[DayView] = load_days(conn, trip_id)

    output_dir.mkdir(parents=True, exist_ok=True)

    files_written: list[Path] = []

    def _write(name: str, content: str) -> None:
        path = output_dir / name
        path.write_text(content, encoding="utf-8")
        files_written.append(path)

    _write("my-maps.csv", render_csv(places))
    _write("my-maps.kml", render_kml(_map_name(trip), places))
    _write("daily-routes.md", render_daily_routes(trip.name, days))
    _write("places-index.md", render_places_index(trip.name, places))
    _write("saveable-places.md", render_saveable_places(trip.name, places))
    _write("README.md", _README)

    conn.execute(
        "UPDATE trip SET my_maps_generated_at = ? WHERE id = ?",
        (datetime.now().isoformat(timespec="seconds"), trip_id),
    )
    conn.commit()

    return GenerationReport(
        files_written=files_written,
        places_total=len(places),
        places_pinned=sum(1 for p in places if p.lat is not None and p.lng is not None),
        places_saveable=sum(1 for p in places if p.google_place_id),
        days_with_routes=sum(
            1
            for d in days
            if any(link.place.lat is not None or link.place.google_place_id for link in d.links)
        ),
    )
